plugins:
  - rubocop-thread_safety

AllCops:
  NewCops: enable

ThreadSafety:
  Enabled: true
  Exclude:
    - 'test/**/*'
    - 'pkg/**/*'

Naming:
  Enabled: false
Style:
  Enabled: false
Layout:
  Enabled: false
Metrics:
  Enabled: false
Lint:
  Enabled: false