version: 2.1

jobs:
  build:
    parameters:
      ruby_version:
        type: string
    docker:
      - image: << parameters.ruby_version >>
    steps:
      - checkout
      - run: ruby --version
      - run: bundle install
      - run:
          name: Run tests
          command: bundle exec rake test:all
      - run:
          name: Rubocop
          command: bundle exec rubocop

references:
  matrix_build: &matrix_build
    build:
      matrix:
        tags: true
        parameters:
          ruby_version:
            - "cimg/ruby:3.2"
            - "cimg/ruby:3.3"
            - "cimg/ruby:3.4"
            - "cimg/ruby:4.0"

workflows:
  version: 2
  commit:
    jobs:
      - <<: *matrix_build
